name: Build and deploy Python app to Azure Web App - mytestapp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Optional: keep if you want to run unit tests; not required for deploy
      - name: Set up Python (for tests only)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Optional: run tests here (if you have them)
      - run: |
         python -m pip install -r azure-python-webapp-hello-3.13/requirements.txt
         pytest -q

      - name: Upload artifact (only the app folder)
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: azure-python-webapp-hello-3.13

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: site

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8E2CAF9FB25845C7864E6A94151BB6D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E30113D04FD94867ADF21AA24D9FAD35 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BDD52ABFD4C64D628A1CD487C4DCB06A }}

      # (One-time) set startup and build flag. Replace <RG> with your resource group.
      - name: Configure Web App (startup + build during deploy)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config set -g qa-resource-group -n mytestapp --startup-file "bash startup.sh"
            az webapp config appsettings set -g qa-resource-group -n mytestapp --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mytestapp'
          slot-name: 'Production'
          package: site
